services:
    lotusjeff.sitemap.sitemap:
        class: lotusjeff\sitemap\controller\sitemap
        arguments:
            - '@auth'
            - '@cache'
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@dispatcher'
            - '%core.php_ext%'
            - '@ext.manager'
    lotusjeff.sitemap.listener:
        class: lotusjeff\sitemap\event\listener
        arguments:
            - '@config'
            - '@template'
            - '@controller.helper'
            - '@request'
        tags:
            - { name: event.listener }
